name: smartvest
description: "IOT based application for a smart vest"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.6
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.6
  percent_indicator: ^4.2.5
  fl_chart: ^1.0.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  table_calendar: ^3.2.0
  cupertino_icons: ^1.0.8
  pigeon: ^25.3.1
  google_sign_in: ^6.3.0
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.1.0
  flutter_blue_plus: ^1.35.5
  health: ^13.0.1
  permission_handler: ^12.0.0+1
  http: ^1.2.1 # ADDED for API calls
  flutter_markdown: ^0.7.3 # ADDED for rendering AI response
  flutter_local_notifications: ^17.1.2 # ADD THIS LINE
  flutter_background_service: ^5.1.0
  google_fonts: ^6.2.1
  mqtt_client: ^10.2.1 # <-- ADD THIS LINE
  flutter_staggered_grid_view: ^0.7.0
  glass_kit: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 26 # Your app's minimum SDK version